root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/filebrowser --tags=mupdf --ldflags=\"-w -s -X 'github.com/gtsteffaniak/filebrowser/backend/common/version.CommitSHA=commitSHA' -X 'github.com/gtsteffaniak/filebrowser/backend/common/version.Version=version'\" ."
  bin = "tmp/filebrowser"
  full_bin = "FILEBROWSER_DEVMODE=true CGO_ENABLED=1 ./tmp/filebrowser -c test_config.yaml"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "http/dist", "http/embed", "swagger/docs"]
  exclude_regex = ["http/(dist|embed)"]
  exclude_unchanged = true
  follow_symlink = false
  log = "air.log"
  delay = 1000 # ms

[log]
  time = true

[misc]
  clean_on_exit = true
