server:
  port: 80
  baseURL:  "/"
  sources:
    - "/srv"
auth:
  signup: false
userDefaults:
  darkMode: true
  disableSettings: false
  scope: "."
  singleClick: false
  permissions:
    admin: false
    modify: false
    share: false
    api: false
