server:
  port: 80
  baseURL:  "/files/"
  logging:
    - levels: "info|error|debug"
  sources:
    - path: "../frontend/tests/playwright-files"
      config:
        defaultEnabled: true
        conditionals:
          folderPaths:
            - value: "excluded"
            - value: "excludedButVisible"
              viewable: true

auth:
  methods:
    noauth: true
frontend:
  name: "Graham's Filebrowser"
  disableDefaultLinks: true
  externalLinks:
    - text: "A playwright test"
      url: "https://playwright.dev/"
      title: "Playwright"
userDefaults:
  permissions:
   realtime: true