server:
  port: 80
  baseURL:  "/"
  logging:
    - levels: "info|error|debug"
  sources:
    - path: "../frontend/tests/playwright-files"
      name: "playwright + files"
      config:
        defaultEnabled: true
    - path: "."
      name: "docker"
      config:
        disableIndexing: true
        defaultEnabled: true
    - path: "/tests/playwright-files"
      name: "access"
      config:
        defaultEnabled: true
        denyByDefault: true
frontend:
  name: "Graham's Filebrowser"
  disableDefaultLinks: true
  styling:
    disableEventThemes: true
    customThemes:
      no-rounded:
        description: "No rounded corners" # The description of the theme to display in the UI.
        css: "no-rounded.css" # The css file path and filename to use for the theme.
  externalLinks:
    - text: "A playwright test"
      url: "https://playwright.dev/"
      title: "Playwright"

auth:
  methods:
    password:
      signup: true